class MatchesGraph:
    def __init__(self, graph_dir: str, max_depth: int = 8, mmap: bool = False) -> None:
        ...

    def get_path(self, player1: str, player2: str) -> list[tuple[str, str, int, int]]:
        ...

    def vcount(self) -> int:
        ...

    def ecount(self) -> int:
        ...

    def has_player(self, nickname: str) -> bool:
        ...
